### ISSUE TITLE
PR check cleanup job is not working

### ISSUE THREAD

**Issue by rhopp** [redhat-developer/che-functional-tests#372]
Logs:
https://ci.centos.org/job/devtools-rh-che-prcheck-cleanup/7/console
Even though the PR cleanup job obviously failed, it's still greeen.
It would be nice to also check, if we have mail notification enabled for this job.

**Comment by rhopp** [comment]
Also - Switch this job to use SA and token auth instead of htpasswd auth.

**Comment by ScrewTSW** [comment]
Easy to fix issue, long wait between the job triggers (once a day)

**Comment by ScrewTSW** [comment]
https://github.com/openshiftio/openshiftio-cico-jobs/pull/840 almighty PR open and waiting

**Comment by ScrewTSW** [comment]
almighty PR merged. Waiting for job to trigger and confirm that it has been fixed.

**Comment by ScrewTSW** [comment]
rh-che pr meged, waiting for the job to trigger

**Comment by rhopp** [comment]
Still not working: https://ci.centos.org/job/devtools-rh-che-prcheck-cleanup/10/

**Comment by ScrewTSW** [comment]
Cleanup job is now running correctly.
